nomeCompleto = str(input('Digite seu nome completo: '))
maiusculas = nomeCompleto.upper()
minusculas = nomeCompleto.lower()
tamanhoTotal = len(nomeCompleto.replace(" ",""))
tamanhoNome = nomeCompleto.split()
print(f'Nome => {nomeCompleto} \nMaiusculo => {maiusculas} \nMinusculo => {minusculas} \nTamanho total => {tamanhoTotal} letras \nPrimeiro nome => {len(tamanhoNome[0])} letras')